name: Build fd.toripota container image
on:
  workflow_dispatch:
  push:
    branches:
      - 'fd.toripota.com'
    tags:
      - '*'
permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64
      use_native_arm64_builder: false
      push_to_images: |
        ghcr.io/rutan/mastodon
      cache: false
      tags: |
        type=ref,event=pr
        type=sha
    secrets: inherit
